### ISSUE TITLE
Backported Fix for the Creation missmatching calculation 

### ISSUE THREAD

**Issue by matfechner** [osism/docker-image-ceph-daemon#31]
Hi @berendt

the last  PR does not fix the reported Bug
the read as following  must be patched:  

https://github.com/ceph/ceph/pull/39270/files

**Comment by berendt** [comment]
At this point, we rely on releases from the upstream. Backports for Ceph within this container are not provided.

**Comment by matfechner** [comment]
Fixed in Upstream 
https://ceph.io/releases/v14-2-17-nautilus-released/

**Comment by berendt** [comment]
@matfechner I updated the base images 8 days ago (https://github.com/osism/docker-image-ceph-daemon/blob/master/.github/workflows/build-docker-image.yml#L32). Please check if we are now on the right Ceph version.

**Comment by matfechner** [comment]
@berendt, thanks a lot,  yes it is the right version now and it works fine
